Fix releasing while prerelase is available
dolittle/establish-context-action pull request #41
Opened 2021-05-14 17:16 UTC by jakhog

## Summary

Summary of the PR here. The GitHub release description is created from this comment so keep it nice and descriptive.

Remember to remove sections that you don't need or use.

### Added

- Describe the added features

### Changed

- Describe the outwards facing code change

### Fixed

- Describe the fix and the bug

### Removed

- Describe what was removed and why

### Security

- Describe the security issue and the fix

### Deprecated

- Describe the part of the code being deprecated and why

2021-05-14 21:55 UTC, jakhog commented
Please have a look at the added specs to make sure that the behaviour is as intended. I'm not 100% sure how this action interacts with the other ones we use - so I might have made some faulty assumptions.

2021-05-17 19:06 UTC, woksin requested changes
Great stuff! There are however two specs I immediately thought of that we probably want:

when finding without a prerelease and there is an older prerelease
when finding without a prerelease and there is a prerelease on same version

2021-05-18 10:37 UTC, jakhog commented on Source/Version/for_CurrentVersionFinder/given/a_version_finder.ts
> +}
Yes, it turned out quite nice :) Had to ad sinon-ts to make it work, but that seemed like a reasonable library to use.

2021-05-18 10:40 UTC, jakhog commented
Added to more specs, I think they cover the scenarios you described.

2021-05-18 10:43 UTC, woksin approved these changes
Nice stuff!

2021-05-18 10:43 UTC, merged